language: node_js
node_js:
  - 0.6

before_script:
  - "curl -o resources/JsTestDriver-1.3.5.jar 'http://js-test-driver.googlecode.com/files/JsTestDriver-1.3.5.jar'"
  - "java -jar resources/JsTestDriver-1.3.5.jar --config jsTestDriver.conf --port 9876 &"
  - "sleep 3"
  - "phantomjs resources/js-test-driver-phantomjs/phantomjs-jstd.js &"
  - "sleep 3"
  - "npm install connect"
  - "node tests/ui/node-server.js &"
  - "sleep 3"
#script: phantomjs tests/ui/siesta-phantomjs.js