language: node_js
node_js:
  - 0.6

before_script:
  - "curl -o resources/JsTestDriver-1.3.5.jar 'http://js-test-driver.googlecode.com/files/JsTestDriver-1.3.5.jar'"
  - "java -jar resources/JsTestDriver-1.3.5.jar --config jsTestDriver.conf --port 9876 &"
  - "sleep 3"
  - "phantomjs resources/js-test-driver-phantomjs/phantomjs-jstd.js &"
  - "sleep 3"
  - "node tests/ui/node-server.js &"
  - "sleep 3"
#script: phantomjs tests/ui/siesta-phantomjs.js

env:
  global:
  - secure: "XTlo9yNKD5M7DsYPFAEUIHkrdAvrem8lZDFIkga0XfvKCt1FYMvgjnQ95AVY\nzryWg4O1pNHThSIP8fanygxpTSpbX/+dyhfakj0A3CP/OU8DLcbVfO/LhpZM\n5o5CDGYCCrLCoJnOHsS1XeM/btcu7XdePqhpz+goLJyuWvXiT70="

after_success:
  - wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
  - heroku plugins:install https://github.com/ddollar/heroku-anvil
  - heroku build -r extjs-cascadedcombobox-widget  -b
    https://github.com/heroku/heroku-buildpack-nodejs.git